version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data
  api:
    build: .
    depends_on:
      - db
    env_file: .env
    ports:
      - "4000:4000"

volumes:
  db-data: